server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_cloud_user?useSSL=false
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userService
mybatis:
  type-aliases-package: com.chen.user.entiy
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.chen: debug