server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_cloud_order?useSSL=false
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderService
  cloud:
    nacos:
      server-addr: localhost:8848
mybatis:
  type-aliases-package: com.chen.order.entiy
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.chen: debug

userService:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则